### ISSUE TITLE
no ui for non-english user profiles

### ISSUE THREAD

**Issue by jsassm** [Cyanoth/Bitbucket-PullRequest-ReviewerGroups#1]
First, thank you very much for your great plugin! This helps a lot!

We recognized only this issue: 
If you have any other language set than english in your bitbucket-account-profil, than the button "_Add Reviewers From Group_" doesn´t show up in the create-pull-request-form.

**Comment by Cyanoth** [comment]
Hi @jsassm,

Thank you for the kind feedback & reporting this issue. 

I am able to reproduce & I understand what is causing this issue. I am working on a fix for this and will let you know once a new version is available.

The fix will resolve the issue of the 'Add Reviewers From Group' button not showing on a language other than English. However, this issue has also highlighted to me that the plugin UI has hardcoded English strings with no l10n option. I have raised a separate issue: https://github.com/Cyanoth/Bitbucket-PullRequest-ReviewerGroups/issues/2 where I will implement localization for this plugin.

Regards,
Cyanoth.

**Comment by Cyanoth** [comment]
Hi @jsassm,

I have created a new release: v0.3.3 which resolves this issue. It has been manually tested on Bitbucket 6.10.5, 7.4.0, 7.6.0 with several different languages, Chrome & Firefox.

This has been submitted & approved on the Atlassian Marketplace (v0.3.3) so you can install it on your Bitbucket instance. 

I will close this issue now, if you have any further issues with this feel free to reopen.  

Thanks,
Cyanoth.
