### ISSUE TITLE
Missing "Add Reviewers From Group" button on PR edit screen (Bitbucket v.v7.17.5)

### ISSUE THREAD

**Issue by komusTeam** [Cyanoth/Bitbucket-PullRequest-ReviewerGroups#4]
Hello!
We've encountered the problem - there's no visible button in PR edit screen.
However, there is one on PR open screen and it works perfectly.

Could you please fix this?

Here're some screenshots.

PR create screen - 
![image](https://user-images.githubusercontent.com/106298175/170428046-ffb1f8f6-9c47-438c-ba43-9857f1dcedff.png)

PR edit screen - 
![image](https://user-images.githubusercontent.com/106298175/170428563-077819b2-5cc6-42f1-b52d-b4a3916f3904.png)

**Comment by Cyanoth** [comment]
Hey @komusTeam,

I've updated the plugin to v0.3.5 resolve the button not appearing in the edit dialog in Bitbucket 7.17.5

I've tested the plugin works on firefox/chrome on bitbucket versions:
Bitbucket 7.6.0
Bitbucket 7.17.5 
Bitbucket 7.21.1 (latest LTS as of the time of writing)

I've pushed the change to Atlassian Marketplace, it should appear after their usual checks. Alternatively you can download the packaged version of the v0.3.5 from the releases page.

Thanks,
Charles.
